<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NutriInsights.Domain\NutriInsights.Domain.csproj" />
    <ProjectReference Include="..\NutriInsights.Infrastructure\NutriInsights.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1a3ad367-5deb-4de6-bd85-c0b2a5a3caef</UserSecretsId>
  </PropertyGroup>

</Project>
