<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-NutriInsights_Web-3ce0b25b-05d1-4db2-838a-86a833044f33</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NutriInsights.Domain\NutriInsights.Domain.csproj" />
    <ProjectReference Include="..\NutriInsights.Infrastructure\NutriInsights.Infrastructure.csproj" />
  </ItemGroup>

</Project>
